### ISSUE TITLE
刘博您好，最近在使用您的PPG-VC语音转换的感觉效果非常好，可以提供训练过程具体操作吗？

### ISSUE THREAD

**Issue by pn1024** [liusongxiang/ppg-vc#14]

**Comment by liusongxiang** [comment]
Hi, readme中给了feature准备，训练的完整描述。

**Comment by pn1024** [comment]
哈哈哈真的假的，大神您好，咨询您一个问题就是，比如说在提取进行第3步，3_compute_spk_devcs.py计算扬声器d向量我的输出仅仅只有一个空文件夹，
然后main训练过程中里面train_fid_list里面train_fid_list.new文件我也不太清楚，太菜了



---原始邮件---
发件人: "Songxiang ***@***.***&gt;
发送时间: 2021年9月18日(周六) 下午3:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liusongxiang/ppg-vc] 刘博您好，最近在使用您的PPG-VC语音转换的感觉效果非常好，可以提供训练过程具体操作吗？ (#14)




 
Hi, readme中给了feature准备，训练的完整描述。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liusongxiang** [comment]
请看一下文档哈
