### ISSUE TITLE
Unable to run convert_from_wav.py; Module nnsp is missing a submodule?

### ISSUE THREAD

**Issue by Iamgoofball** [liusongxiang/ppg-vc#2]
![cmd_2WyWrZJ55f](https://user-images.githubusercontent.com/4081722/121953694-baadf480-cd12-11eb-9279-c9083c102b8f.png)

text:
`(base) F:\ppg-vc>python convert_from_wav.py --ppg2mel_model_train_config .\bilstm-vctk-libritts460-oneshot\bilstm_ppg2mel_vctk_libri_oneshotvc.yaml --ppg2mel_model_file .\bilstm-vctk-libritts460-oneshot\step_250000.pth --src_wav_dir F:\p5_characters\Ann\audio --ref_wav_path F:\p5_characters\Akechi\audio\ve370_002_00083.wav -o .\output_ann_to_akechi
Traceback (most recent call last):
  File "convert_from_wav.py", line 11, in <module>
    from src.mel_decoder_mol_encAddlf0 import MelDecoderMOL
  File "F:\ppg-vc\src\__init__.py", line 4, in <module>
    from .mel_decoder_lsa import MelDecoderLSA
  File "F:\ppg-vc\src\mel_decoder_lsa.py", line 20, in <module>
    from .rnn_decoder_lsa import Decoder
  File "F:\ppg-vc\src\rnn_decoder_lsa.py", line 5, in <module>
    from nnsp.ctc_seq2seq_ppg_vc.lsa_attention import LocationSensitiveAttention
ModuleNotFoundError: No module named 'nnsp.ctc_seq2seq_ppg_vc'`

I'm on Python 3.8, latest version of nnsp is installed via pip.

**Comment by liusongxiang** [comment]
sorry for the inconveience. I removed the dependencies. Please try again.
